SYS_TARGET_PROJECT := mssi_64_cn
SYS_TARGET_PROJECT_FOLDER := device/mediatek/system/$(SYS_TARGET_PROJECT)
MTK_TARGET_PROJECT := k69v1_64_k419
MTK_TARGET_PROJECT_FOLDER := $(LOCAL_PATH)

-include $(SYS_TARGET_PROJECT_FOLDER)/sys_$(SYS_TARGET_PROJECT).mk
-include $(LOCAL_PATH)/vnd_$(MTK_TARGET_PROJECT).mk

PRODUCT_NAME := full_k69v1_64_k419

